### ISSUE TITLE
Remove version display on the frontpage.

### ISSUE THREAD

**Issue by legremz** [dani-garcia/bw_web_builds#142]
Hello,

Displaying version information on unauthenticated pages is a bad security practice as it give attackers quick and easy informations to seek working flaws.

Security by obscurity might be controversial on some points but displaying version on an unauthenticated page give too much information to possible attackers. 
Displaying this information to unauthenticated users offers no other purposes than weakening the security of the instance.

Can this be remove in future releases ?

**Comment by BlackDex** [comment]
If you really think this is needed i suggest to report this upstream since that would benefit all Bitwarden users, not just Vaultwarden.

Also, to maybe scare you even more, the `/api/config` endpoint is accessible without any authentication, and displays the server version. Also, not something we can fix or change, since the clients need access to this information.

**Comment by legremz** [comment]
Thanks for the quick reply.

If the endpoint `/api/config` gives off the server version so easily , the version displayed on the frontpage seem less important all of a sudden...
