### ISSUE TITLE
Problems when changing the collection in an existing entry

### ISSUE THREAD

**Issue by stefanpflug** [dani-garcia/bw_web_builds#168]
Server Installed 1.30.5
Web Installed 2024.5.0
Database MySQL: 8.0.36

There is a structure like this:
/Collection
/Collection/Subfolder

If I go to an element below "/Collection" in the web client and change the collection to "/Collection\Subfolder",
the entry remains visible below /Collection.
The entry is only displayed in the correct collection when the page is reloaded.

If the Windows client is opened at the same time, you can see that the entry is already being moved in real time, but the web client apparently does not receive any feedback about this (or does not process it).

In the browser plugin (Firefox and Chrome), a resync must be performed to see the moved entry in the selected collection.
In the Windows client, a change of collections is sufficient to see the change.

When a rollback to v2024.3.1 is performed, it works as expected in the web client, but the action is acknowledged with an error message in the browser plugin and in the Windows client.

Greetings 

Stefan

**Comment by BlackDex** [comment]
Vaultwarden only stores what the client sends. The clients are maintained by Bitwarden and we only patch it so it will work correctly with Vaultwarden.

I would suggest to test the latest release v1.31.0 (released this week) or our `testing` tagged images which have a newer web-vault version and might have solved your issue. Other than that we can't really do anything about this, since we do not maintain the clients.

Because of that, I'm going to close this ticket.
