### ISSUE TITLE
Forgot to update "version.json" in Version 2.18.1b?

### ISSUE THREAD

**Issue by IchSchreiGleich** [dani-garcia/bw_web_builds#26]
In the downloadable package "bw_web_v2.18.1b.tar.gz" the string in "version.json" still points to 2.18.1. Is this correct? If I changed to "b", the webinterface is satisfied and dont want to update anymore.

**Comment by jjlin** [comment]
Yes, it's correct. In general, the web vault version and bitwarden_rs version need to be properly matched, and users shouldn't update them independently. The proper matching versions are whatever is bundled together in the Docker image.

Because the web vault should not be updated independently, the admin interface in the latest bitwarden_rs version has removed the web vault version check.

**Comment by BlackDex** [comment]
I didn't removed it when not running within docker.
Because self-compiled could still benefit from this check.
Maybe we do need to update version file also when we have a subsequent patch letter.

**Comment by jjlin** [comment]
Even if it's running outside of Docker, I don't think it should show the latest version, since that's implying that the user should upgrade to it. If anything, it should pull the `vault_version` variable out of `Dockerfile.j2` to show the proper matched version.

**Comment by BlackDex** [comment]
I already have some logic regarding testing and latest based upon the commit hash available or not.

So, maybe i can use that to select the correct version for which vault version is the latest, but then still this would go wrong. Since version.json does not hold the letter patched version.

So it would not solve the issue at hand, and, i this case the user should update, but we didn't updated that file. So somewhere we need to make sure for the users which version they are running. And not changing version.json will not help.

**Comment by jjlin** [comment]
Yeah, I would prefer not to change an upstream file, though. If we need the bitwarden_rs-specific version, it's probably better to just add our own file. Perhaps something like `bwrs-web-version` that contains just the version.

**Comment by BlackDex** [comment]
That sounds like a good option.
I think we can add this simply in the build and docker files.
