### ISSUE TITLE
Hide some settings (or do they have any use?)

### ISSUE THREAD

**Issue by jonathanmmm** [dani-garcia/bw_web_builds#4]
Hi dani-garcia,

I am using mprasil/bitwarden:latest on debian with docker-ce.

The server version shows: Version 2.10.0 (on https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.8.0 is written Version 2.9.0 is this a typo or is it still 2.10.0)

Also: in the web-vault using mybitwarden.com/#/settings/subscription the website just loads an loads and nothing is there. Is this used for anything or could it be hidden in the settings?

Also in organizations is the same happening:
mybitwarden.com/#/organizations/c18a1e04-6cba-420c-83c3-73a4711e7810/settings/subscription

Also just loading and loading.

Maybe this could be hidden or is this used for donating (through buying a premium subscription) to the original Bitwarden from Kyle?

Also I would be happy if someone could answer these two questions:
Just now I am using the mprasil/bitwarden:latest, will soon maybe install the raspberry version (is this in the functionallity somehow different, maybe older or is just the kernel thing, not an expert in this part different?)
And the web vault is the official one build in and some files are changed to make it work, right?

Thanks and great work, this way bitwarden can also run on small systems. Maybe in the future this becomes an official part of bitwarden or bitwarden_rs can get also some security audit (many people may not like to use unofficial repositories with no way to know if it is the same way secure. I will use it, as many people are using it, but things like a security audit would make it more trustable or more confortable. But I know that such thing would be probably expensive).

**Comment by dani-garcia** [comment]
If you are using the `latest` image, then you are using the latest commit from the main repo, which is already using the vault 2.10.0. The last 1.8.0 release is available in the image `mprasil/bitwarden:1.8.0`.

The subscriptions are a new thing in one of the latest vaults, I pushed a patch and updated the latest vault build to hide them. But we'll have to wait untill the next change in the main repo for the images to be rebuilt.

To contribute upstream it's simpler to either buy a plan in the official vault or to donate to their paypal account (We have some links in the wiki of the main project)

The difference between images is just what architecture they are built for, the `latest` image, for example, is built for x86 computers, so it doesn't work on ARM devices like the raspberry pi, so we also provide the `raspberry` image.

About a possible audit, all sensitive info that we receive is already encrypted in the client, which should solve most peoples worries, as we really can't do anything with it. Ultimately, I'd love to have a security expert review the code, if only to learn of any potential mistakes, but I can't justify spending the amount of money that is required for a serious security audit, specially when we are using a pretty new language like Rust, I can't imagine there are a lot of Rust security experts a the moment!

**Comment by jonathanmmm** [comment]
Thanks for your quick and long answer.

I mean with vault 2.9.0 that the Release description of 1.8.0 says 2.9.0 but its 2.10.0 (in the release tag)

OK, so when vault 2.11.0 comes out from Kyle you will (or can only then?) bring new changes, because it depends on it?
Or you mean with Main repo the bitwarden_rs repo?

I like to know more about how this all repo thing with web vault attached to the official repo works. Did I Miss Something in the Wiki or so?

Right, the clients encrypt everything and a Security Audit was Made (as official clients). But the web vault in bitwarden_rs is slightly different. So for people who worry about that should only use the clients and only the web vault in the beginning for setting Up Organisations (if wished), right?

**Comment by dani-garcia** [comment]
The versions from the main bitwarden_rs repo are independend from the web vault builds, I try to create a new release here as soon as there is a new release in the upstream web vault, and after some testing I'll update the bitwarden_rs Dockerfiles to use the new version. This will make the latest web vault available in the `latest` image. Some time after, when I believe the number of changes are enough, I'll create a new release for the bitwarden_rs project, but again, those are not necessarily linked to the web vault version.

Currently, the latest release of the web vault is 2.10.0, which is available in the master branch of bitwarden_rs and the `latest` image. The last bitwarden_rs release is 1.8.0 which is a bit older and uses vault 2.9.0. We have something like this now:

```
Bitwarden_rs       Web vault
latest / master    2.10.0
1.8.0              2.9.0
1.7.0              2.8.0
```

About the changes I made to hide those options, the last release of the web vault is already updated, but the docker images won't be rebuilt until the next change to the main bitwarden_rs repo.

This repo exists because we need to make a couple of changes to the official vault to make it work, they shouldn't change anything audit-wise. Those changes are:
- Disabling analytics and changing the URL to the local server
- Changing how U2F devices are registered, because some browsers return self-signed certificates otherwise, this won't affect anynone who doesn't use U2F
- Visual changes to hide unused options, like the ones I just made

The reason we provide the compiled binaries here is that their compilation takes a big amount of RAM, so it used to cause problem for those building it in low power devices like Raspberries.

About whether to use the web vault vs the other clients, that's your choice, really. You could build the web vault yourself using the upstream code and applying the patch available here (which is pretty small and easy to read) and you could also build the bitwarden_rs code manually to be safer, it all depends on your threat model.

**Comment by jonathanmmm** [comment]
OK, thanks for your answer, I will close this now.
