### ISSUE TITLE
MFA code hardcoded in UI dialogs as 6 digits

### ISSUE THREAD

**Issue by knightian** [dani-garcia/bw_web_builds#47]
Hello, I'm using a larger than 6 digit code for the MFA code as set in the admin area.

However it seems that the web vault is hard coded to always ask for a 6 digit code even when it is set to more digits.

Is it possible to make that value be read from the config instead of a hard coded value of 6?

<img width="423" alt="Screen Shot 2021-09-08 at 1 55 53 pm" src="https://user-images.githubusercontent.com/72685601/132444059-bde55efd-9d93-4c46-be9b-de674ea818cb.png">

**Comment by BlackDex** [comment]
No it is not.
This is hardcoded into the language files.
Besides that we do not have anything modifiable at runtime for the web-vault.

**Comment by knightian** [comment]
> No it is not

What is not? It's hardcoded and only shows "6 digits" even when I set 10 digits as the code.



> Besides that we do not have anything modifiable at runtime for the web-vault

So it is not possible to display the true value/ We must always see a wrong value?

**Comment by jjlin** [comment]
The docs clearly say the clients are hardcoded to say 6 digits:

https://github.com/dani-garcia/vaultwarden/blob/main/.env.template#L149-L152

Generally we try to minimize changes to the clients, as the goal of the project isn't to produce a custom client. This also isn't an option that upstream Bitwarden even offers, so if you want it to say the correct thing, stick to the default of 6 digits. Otherwise you can build your own version of the web vault that is hardcoded to whatever you're using, but even then, the other clients (mobile, browser, desktop) will still say 6 digits.

**Comment by knightian** [comment]
> Generally we try to minimize changes to the clients, as the goal of the project isn't to produce a custom client. This also isn't an option that upstream Bitwarden even offers, so if you want it to say the correct thing, stick to the default of 6 digits. Otherwise you can build your own version of the web vault that is hardcoded to whatever you're using, but even then, the other clients (mobile, browser, desktop) will still say 6 digits.

Gotcha, ok, yea makes sense I didn't realise upstream was limited to 6 and so didn't consider the other clients either.
