### ISSUE TITLE
repack into own directory

### ISSUE THREAD

**Issue by hboetes** [dani-garcia/bw_web_builds#7]
Currently the vault directory does not have a leading directory. May I kindly request packing it with a predictable name? This makes packaging easier and prevents surprises when people do not `tar tf` the tarball first.

So the traditional output would look like this:
```
% tar tf bw_web_v2.12.0.tar.gz|head -n 5
bw_web_v2.12.0/app/
bw_web_v2.12.0/app/main.553962d815b08b8f918b.css
bw_web_v2.12.0/app/main.553962d815b08b8f918b.css.map
bw_web_v2.12.0/app/main.553962d815b08b8f918b.js
bw_web_v2.12.0/app/main.553962d815b08b8f918b.js.map
```

Thanks!

**Comment by mqus** [comment]
I just tried to package the precompiled files and also stumbled on this. I can try to fix myself it but I can't promise anything ;)

**Comment by mqus** [comment]
My suggestion from a very brief look over it:
remove
https://github.com/dani-garcia/bw_web_builds/blob/9648d630de77d5f8abae5ef7574443a3b34a3821/package_web_vault.sh#L79
and change `./*` to `build` here:

https://github.com/dani-garcia/bw_web_builds/blob/9648d630de77d5f8abae5ef7574443a3b34a3821/package_web_vault.sh#L80

~Afterwards, we'll have to change the documentation~
Actually, we probably won't have to change the documentation because https://github.com/dani-garcia/bitwarden_rs/wiki/Building-binary already refers to the `build` directory.
