### ISSUE TITLE
2022.10.0 cuts off "Send" menu items

### ISSUE THREAD

**Issue by tessus** [dani-garcia/bw_web_builds#85]
The last version cuts off the menu items for Send:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/223439/196056753-e3459875-54f7-4af8-bd9a-3ad2949d5faa.png">

All Sen...
Te..
Fi..

This makes no sense, since there's more than enough space.

**Comment by BlackDex** [comment]
Seems to work just fine on my browser.
Have you tried an cognition/private tab or other browser?
It could be some extension maybe, or maybe the zoom level.

**Comment by tessus** [comment]
I tried with 2 browsers (one w/o extensions) and also Private Browsing on both.

Unfortunately I still experience the same issue. Also, no matter the zoom level, it's always the same.

**Comment by tessus** [comment]
Ha, I was able to narrow it down. It does not happen with Safari 14.1.2. Only with Firefox 105.0.3 (64-bit) and Firefox Developer Edition 106.0b9 (64-bit).

It also works on Chrome 88.0.4324.192 (yes, I know it's an ancient version, since I don't use Chrome and locked it to that version).

Apparently it's a problem with the Firefox engine.

**Comment by BlackDex** [comment]
This also seems to happen on `vault.bitwarden.com`, so, this is not something we can fix on our side.
It seems to have been reported upstream already here: https://github.com/bitwarden/clients/issues/3789
And also fixed via here: https://github.com/bitwarden/clients/pull/3791

So, we just have to wait until they release a new version of the web-vault, because backporting only this fix and creating a new release is a bit to much i think 😄 .

But, thanks for reporting!

**Comment by tessus** [comment]
Thanks for the info.
